export const AGREGAR_MOTIVO = 'AGREGAR_MOTIVO';
export const AGREGAR_FECHA = 'AGREGAR_FECHA';
export const AGREGAR_CONTENIDOCOGNITIVO = 'AGREGAR_CONTENIDOCOGNITIVO';
export const AGREGAR_CONTENIDOMEDICA = 'AGREGAR_CONTENIDOMEDICA';
export const AGREGAR_CONTENIDONUTRICIONAL = 'AGREGAR_CONTENIDONUTRICIONAL';
export const AGREGAR_CONTENIDOSOCIA = 'AGREGAR_CONTENIDOSOCIA';
export const AGREGAR_CONTENIDOMOTORA = 'AGREGAR_CONTENIDOMOTORA';
export const AGREGAR_CONTENIDOCOMUNICACION = 'AGREGAR_CONTENIDOCOMUNICACION';
export const AGREGAR_ANTECEDENTE = 'AGREGAR_ANTECEDENTE';
export const AGREGAR_OBJETIVO_COGNITIVO = 'AGREGAR_OBJETIVO_COGNITIVO';
export const AGREGAR_OBJETIVO_COMUNICACION = 'AGREGAR_OBJETIVO_COMUNICACION';
export const AGREGAR_OBJETIVO_MEDICA = 'AGREGAR_OBJETIVO_MEDICA';
export const AGREGAR_OBJETIVO_MOTORA = 'AGREGAR_OBJETIVO_MOTORA';
export const AGREGAR_OBJETIVO_NUTRICIONAL = 'AGREGAR_OBJETIVO_NUTRICIONAL';
export const AGREGAR_OBJETIVO_SOCIA = 'AGREGAR_OBJETIVO_SOCIA';

export const AGREGAR_ACTIVIDAD_COGNITIVO = 'AGREGAR_ACTIVIDAD_COGNITIVO';
export const AGREGAR_ACTIVIDAD_COMUNICACION = 'AGREGAR_ACTIVIDAD_COMUNICACION';
export const AGREGAR_ACTIVIDAD_MEDICA = 'AGREGAR_ACTIVIDAD_MEDICA';
export const AGREGAR_ACTIVIDAD_MOTORA = 'AGREGAR_ACTIVIDAD_MOTORA';
export const AGREGAR_ACTIVIDAD_NUTRICIONAL = 'AGREGAR_ACTIVIDAD_NUTRICIONAL';
export const AGREGAR_ACTIVIDAD_SOCIA = 'AGREGAR_ACTIVIDAD_SOCIA';
export const AGREGAR_ENCUADRE = 'AGREGAR_ENCUADRE';
export const AGREGAR_CONCLUSION = 'AGREGAR_CONCLUSION';

export const ELIMINAR_OBJETIVO_COGNITIVO ='ELIMINAR_OBJETIVO_COGNITIVO';
export const ELIMINAR_OBJETIVO_COMUNICACION = 'ELIMINAR_OBJETIVO_COMUNICACION';
export const ELIMINAR_OBJETIVO_MEDICA = ' ELIMINAR_OBJETIVO_MEDICA';
export const ELIMINAR_OBJETIVO_MOTORA = ' ELIMINAR_OBJETIVO_MOTORA';
export const ELIMINAR_OBJETIVO_NUTRICIONAL = 'ELIMINAR_OBJETIVO_NUTRICIONAL';
export const ELIMINAR_OBJETIVO_SOCIA ='ELIMINAR_OBJETIVO_SOCIA';

export const ELIMINAR_ACTIVIDAD_COGNITIVO = ' ELIMINAR_ACTIVIDAD_COGNITIVO';
export const ELIMINAR_ACTIVIDAD_COMUNICACION ='ELIMINAR_ACTIVIDAD_COMUNICACION';
export const ELIMINAR_ACTIVIDAD_MEDICA = 'ELIMINAR_ACTIVIDAD_MEDICA';
export const ELIMINAR_ACTIVIDAD_MOTORA = 'ELIMINAR_ACTIVIDAD_MOTORA';
export const ELIMINAR_ACTIVIDAD_NUTRICIONAL = 'ELIMINAR_ACTIVIDAD_NUTRICIONAL';
export const ELIMINAR_ACTIVIDAD_SOCIA = ' ELIMINAR_ACTIVIDAD_SOCIA';